version: '3.8'

services:
  etl-service:
    build:
      context: ./etl-service # Ubicación del Dockerfile del ETL
    container_name: etl_service
    volumes:
      - ./etl-service/data:/usr/src/app/data # Monta la carpeta data en el contenedor
      - ./scrapped_data:/usr/src/app # Monta la carpeta del servicio en el contenedor
    environment:
      - TZ=America/Argentina/Buenos_Aires
    command: cron

  crud-service:
    build:
      context: ./CRUD-service # Ensure this path is correct
    container_name: crud_service
    volumes:
      - ./scrapped_data:/usr/src/app/ # Ensure this mounts correctly
    environment:
      - TZ=America/Argentina/Buenos_Aires
